name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv ruff pytest pytest-cov
          make install
          
      - name: Run linter
        run: |
          make lint
          
      - name: Run tests
        run: |
          make test
          
      - name: Run test coverage
        run: |
          make test-coverage
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Greshn1k92_python-project-50
            -Dsonar.organization=greshn1k92
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.xunit.reportPath=test-results.xml
            -Dsonar.sources=gendiff
            -Dsonar.tests=tests
            -Dsonar.python.xunit.reportPath=test-results.xml
            -Dsonar.coverage.exclusions=tests/** 